apiVersion: v2
name: core-microservice-template
description: Универсальный шаблон для развертывания микросервисов в Kubernetes
type: application

# Версия самого чарта (меняется при правке шаблонов)
version: 1.0.0

# Версия приложения (например, тег образа Docker)
appVersion: "1.22.0"

dependencies:
  - name: redis
    version: 17.4.0
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: redis.enabled