{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # Используем наш хелпер для названия
  name: {{ include "core-microservice.fullname" . }}
  labels:
    {{- include "core-microservice.labels" . | nindent 4 }}
spec:
  rules:
    # Берем хост (домен) из values.yaml
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                # Связываем Ingress с сервисом, созданным на прошлом шаге
                name: {{ include "core-microservice.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
