{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "core-microservice.fullname" . }}-gateway
spec:
  selector:
    istio: ingressgateway # Это должно совпадать с лейблом пода в istio-system
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ .Values.istio.host | quote }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "core-microservice.fullname" . }}-vs
spec:
  hosts:
  - {{ .Values.istio.host | quote }}
  gateways:
  - {{ include "core-microservice.fullname" . }}-gateway
  http:
  - route:
    - destination:
        host: {{ include "core-microservice.fullname" . }}
        subset: v1
      weight: {{ .Values.istio.canary.v1Weight }}
    - destination:
        host: {{ include "core-microservice.fullname" . }}
        subset: v2
      weight: {{ .Values.istio.canary.v2Weight }}
{{- end }}
